server:
  port: 8080
  compression:
    enabled: true
  connection:
    timeout: -1
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-stream
    username: stream
    password: stream
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

